# Project: Project1
# Makefile created by Dev-C++ 5.0.0.7

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = 
OBJ      = fileIO.o LAB524Rand.o main.o timer.o $(RES)
LINKOBJ  = fileIO.o LAB524Rand.o main.o timer.o $(RES)
LIBS     = -L"D:/Program_Files/Dev-Cpp/lib" -L"D:/Program_Files/Dev-Cpp/lib/gcc" -static-libstdc++ -static-libgcc  
INCS     = -I"D:/Program_Files/Dev-Cpp/include" 
CXXINCS  = -I"D:/Program_Files/Dev-Cpp/include" 
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS   = $(INCS)  
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Project1.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Project1.exe" $(LIBS)

fileIO.o: fileIO.cpp
	$(CPP) -c fileIO.cpp -o fileIO.o $(CXXFLAGS)

LAB524Rand.o: LAB524Rand.cpp
	$(CPP) -c LAB524Rand.cpp -o LAB524Rand.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

timer.o: timer.cpp
	$(CPP) -c timer.cpp -o timer.o $(CXXFLAGS)
